version: '3'
services:

  web-php:
    image: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/apache2/php7.1/sites-available:/etc/apache2/sites-available
      - ./docker/apache2/php7.1/etc/cmd/entrypoint.sh:/entrypoint.sh
      - ./docker/apache2/php7.1/etc/ssl:/etc/apache2/ssl
    working_dir: /var/www/html
    environment:
      # Custom user ID and group ID to start
      # Get auto if not set
      DCUID: ${DCUID}
      DCGID: ${DCGID}
      MAIN_DOMAIN: ${MAIN_DOMAIN}
      REST_DOMAIN: ${REST_DOMAIN}
      BACKEND_DOMAIN: ${BACKEND_DOMAIN}
      GITHUB_KEY: ${GITHUB_KEY}
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/mysql/5.7/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
